### PR TITLE
+flash, roar, whirlwind, wing attack battle anims

### PR DESCRIPTION
**Pull request by 1iminal**
Also updated Growl metadata to use new `user_cry` tag instead of having this stuff hardcoded

### CODE REVIEW

**Comment by SheerSt** [comment]
Slight issue regarding the Flash animation. I've had users report in the past that very quickly flashing black and white colors is a problem, especially since the game can be fullscreened. This was the case with the Low Kick animation, my solution was to replace all of the flashing with a single inverse_colors effect. Let me know your thoughts on the best way to handle this. It might be nice to somewhere keep a backup of the 'accurate' animation, maybe?

I'm sorry for taking so long to get back on these. I have been backlogged recently and am trying to catch up.

**Comment by SheerSt** [comment]
I've looked through your added animations and they're all very accurate, I really appreciate that. Thank you for being so detailed and also for digging in and doing pieces of code.

**Comment by 1iminal** [comment]
>I'm sorry for taking so long to get back on these. I have been backlogged recently and am trying to catch up.

I have no problem with this, please take your time.


As for the flashing issue, I think it's possible to add some kind of "seizure-free mode" user setting, track flashing programmatically and disable it when change between `inverse_colors` and normal colors occurs too often, for example by saving the frame number when `inverse_colors` is called in LoadAndPlayAnimation class and deny turning it off until a certain amount of frames has passed.
Personally I don't have issues with flashing and I'd hate to see moves being changed for everyone because of few people who do.

**Comment by SheerSt** [comment]
> As for the flashing issue, I think it's possible to add some kind of "seizure-free mode" user setting, track flashing programmatically and disable it when change between inverse_colors and normal colors occurs too often, for example by saving the frame number when inverse_colors is called in LoadAndPlayAnimation class and deny turning it off until a certain amount of frames has passed.
> Personally I don't have issues with flashing and I'd hate to see moves being changed for everyone because of few people who do.

I agree that I dislike changing the animations. However the feedback in this regard has been very strong, I think it's affecting a decent number of people. I agree with your idea for how to fix it. imo the 'photosensitive mode' should be enabled by default, and able to be turned off using the settings.txt file.

I should note that I kept a backup of the correct/accurate metadata.out for Low Kick if we need that in the future.

**Comment by SheerSt** [comment]
@Liminalia If you can, I need you to message me on discord sometime so I can coordinate with you.

**Comment by SheerSt** [comment]
I need to perform a change to the pokemon-wilds.git repo that will cause your local commits to diverge, and you will need to re-pull the repo. This will mess up any local branches you have. I was thinking you could push all of your local changes and I can commit them to master and perform the change. Either that or I can go ahead and do it and you will need to reapply your changes locally. Lmk what you think, sorry to inconvenience you like this.

**Comment by SheerSt** [comment]
@Liminalia I had to go ahead with the change. Please be careful **not** to pull the pokemon-wilds.git repo as it may overwrite your existing work. I would recommend pulling pokemon-wilds.git into a separate directory, and then re-applying any of your uncommitted changes in that new directory. Really sorry to inconvenience you like this, I shouldn't need to do this again.

This only applies to the pokemon-wilds repo, I left the code repo untouched.

**Comment by 1iminal** [comment]
No problem

>If you can, I need you to message me on discord sometime so I can coordinate with you.

I've sent you a friend request, `lm_#3526`

**Pull request merged**
