### PR TITLE
Update README's explination of resource gathering

### PR DESCRIPTION
**Pull request by skeddles**
I've been playing for at least 10 hours, and still had no idea how to get silky thread and other pokemon related resources. This guide an many others on the internet just say "get" it from pokemon, but dont specify what that means. I assumed the pokemon dropped them upon defeat (because that's how most video games work). I updated the answer to "How do I gather resources?" to include a line about getting materials from pokemon.

I don't think it's really necessary to list the types of pokemon that know each move because part of the fun is catching them to see what moves they have.

### CODE REVIEW

**Comment by wilzorve** [comment]
Every pokemon type has their own specific ressources.
To get them you need:

1 Have a pokemon with the type your are looking for (Tamed*** and NOT wild) 



2 Drop your pokemon in the map in the RIGHT environnement. 

Tips : You can pick and drop right away some friendly base pokemon in the wild without battle to make them bond to you.
Very Usefull in the next step 



3 Interact with him 
***Note : even if you pick and drop a new wild pokemon in it's natural spawning area, it can be uneasy. A lot of pokemon need to be move elsewhere of their spawn area to be happy.


If he is looking HAPPY: 

good, wait around 1 in-game days and come back, he may have a ressource for you. You can only get 1 ressource per day. So own several pokemon it's a MUST have to farm pokemon's ressources   you need.

If right place is small; terraform or fence your pokemon so he don't go too far



However, If he look UNEASY (unconfortable) in this place, try further/another area or change your surrounding tiles (terraformation)*

*tree / flower / be in water / rock / sand / snow / clay ... and so on, have an effect on the happiness of your pokemon 
Note : single type pokemon have LESS NEED than the double type. So some pokemon are much easier to please as other have 2 type. 

I haven't play for a while so i don't remember well but 

To me seem : 
insect type like flowers tiles, 
flying type like big trees (like  2*2 tile not the small bushes), 
fire type need volcanic activities area 

and so on..

And they give

fire ) charcoal ?
insect ) silky thread
electrick ) magnet 
flying ) soft feather
normal ) manure
dark ) dark energy
psy) psy energy ?
water) hard Scale ?
ground) soft sand

And many more



Well it isn't the best guide, I m sure there are much more to tell. But that the essential to understand how Pokewilds works

**Comment by Pongadeedle-1** [comment]
Interact with tame pokemon to get items
ghost- life force
Normal-manure
Dark-Dark energy
electric-magnet
fire-charcoal
Steel-metal coat
fairy-stardust
ground-soft sand 
Dragon- Dragon scale and dragon fang(rare)
psychic-psy energy
Bug-  silky thread
Water-hard shell
Ice- never melt ice
So those were the normal ones
here are the special ones
Mewtwo, regi's and unkown drop ancient powder
Shuckle berry juice
combee and beedrill line honey
sableye- all evolutionary stone
Miltank-moo moo milk (really good)
Applin sweet apple
Delibird- random item
Staryu and starmie give star piece

**Comment by skeddles** [comment]
these are spoilers in my opinion: they should not be included in the guide, or anywhere. figuring out which pokemon gives what is part of the game.

**Comment by Pongadeedle-1** [comment]
It's not too much of a spoiler

**Comment by Pongadeedle-1** [comment]
dragon fang is rare so some people might think you need a special pokemon to obtain it

**Comment by Pongadeedle-1** [comment]
also some people might not know how to get berry juice

**Review by SiriusGG — COMMENTED** [review]
The suggested change is short, comprehensive, limitted to the most important information and does not spoiler exact item locations.

**Review by SiriusGG — APPROVED** [review]

**Comment by fourlastor** [comment]
Thank you for the PR! Unfortunately this isn't the place for this kind of guide

https://pokewilds.fandom.com/wiki/Pokewilds Wiki has a lot more info which could help, we might work on the wiki eventually but for now we don't have the time to focus on it

**Comment by SiriusGG** [comment]
> Thank you for the PR! Unfortunately this isn't the place for this kind of guide
> 
> https://pokewilds.fandom.com/wiki/Pokewilds Wiki has a lot more info which could help, we might work on the wiki eventually but for now we don't have the time to focus on it

I think you should take a look at the actual file change, because I do think that this is the right place for it. It is only one line in the README.md rewritten to be more complete and this file is tied to this repository.

**Comment by fourlastor** [comment]
You're right, sorry for being hasty and thanks for the feedback!

**Pull request merged**
