### PR TITLE
+some generic moves battle anims

### PR DESCRIPTION
**Pull request by 1iminal**
Battle animation for Razor Leaf (enemy side)

### CODE REVIEW

**Comment by SheerSt** [comment]
@Liminalia I tried them out and they look good. The volume levels sound correct to me.

I did notice a slight issue with doubleslap, in pokemon gold the animation goes 'slap-left, slap-right, slap-left, ...'. Maybe the attack animation could be split into two (doubleslap_left_player_gsc, doubleslap_right...) and some code added to alternate between those two?

Regarding tackle - there is a metadata tag `[player|enemy]_translate_x` that could move the friendly/enemy sprite during the animation. I have some code I used to rip the body slam animation that will generate that metadata; however it requires the friendly/enemy sprite to be non-transparent.
```
    # Detect friendly/enemy sprite translations in the x direction
    if any([d in dir_name for d in ['tackle']]):
        # r and y values are arbitrary and depend on the friendly/enemy pokemon sprite
        # may have to experiment with different values
        r = range(35, 50)
        y = 83
        m = 'player_translate_x:'
        if 'enemy' in dir_name:
            r = range(108, 156)
            y = 41
            m = 'enemy_translate_x:'
        for x in r:
            r,g,b = base_img.getpixel((x,y))
            # Check for translate
            for j in range(len(is_translate)):
                k = is_translate[j]
                if not k:
                    continue
                if x+k < width and x+k >= 0 and im.getpixel((x+k,y)) != (r,g,b):
                    is_translate[j] = False
        for translate in is_translate:
            if not translate:
                continue
            frame_metadata += [m+str(translate)]
```
Or it could be done manually I suppose. Or we could just leave it as-is, lmk what you think.

I have similar code to detect sprite translation in the y-direction.

**Comment by 1iminal** [comment]
I agree with issues mentioned.

Class that calls animations should have a private integer variable (initially set to 0) and in cases when certain multi-turn moves are called (Double Kick, Double Slap) it should increment this variable by one every turn of that move and run _left/_right animation depending on if the variable is even or odd (resetting the variable after the last turn), this is the way I see to implement this feature.

Regarding Tackle yeah, now I see that making sprites transparent was a bad idea. I edited the ROM again and changed sprites to be solid RGB 255,0,0 red this time and almost got it to work with the x transition detection block you provided. We definitely shouldn't leave it as is if there's a way to improve it.
The y transition detection block would be helpful too for moves like Splash and Take Down, I think these should've been included in the script initially.

I'll commit the updated Tackle anim later, Double Slap should be probably left as is until corresponding logic is implemented. 

**//UPD**
`metadata = 'enemy_translate_x:'` should be `m = 'enemy_translate_x:'` in x transition detection block

**Comment by 1iminal** [comment]
Double Kick only hits once, it needs looking into it

**Comment by SheerSt** [comment]
This is the y translate code.
```
    # Detect friendly/enemy sprite translations in the y direction
    if any([d in dir_name for d in ['body_slam']]):
        is_translate = list(range(-32, 41))
        # r and y values are arbitrary and depend on the friendly/enemy pokemon sprite
        # May have to experiment with different values
        r = range(32, 60)
        x = 38
        m = 'player_translate_y:'
        if 'enemy' in dir_name:
            r = range(12, 35)
            x = 130
            m = 'enemy_translate_y:'
        for y in r:
            r,g,b = base_img.getpixel((x,y))
            # Check for translate
            for j in range(len(is_translate)):
                k = is_translate[j]
                if not k:
                    continue
                if y+k < height and y+k >= 0 and im.getpixel((x,y+k)) != (r,g,b):
                    is_translate[j] = False
        for translate in is_translate:
            if not translate:
                continue
            frame_metadata += [m+str(translate*-1)]
```

I didn't have a chance to test it on the romhack, the values in `range()` may need to be tweaked to work there.

There are some animations where the screen shakes, there are metadata tags screen_translate_y and screen_translate_x to handle that. In order to rip that metadata in the past, I think I just replaced the player|enemy_translate_x|y tags in metadata.out to their screen_translate_x|y equivalent.

**Comment by SheerSt** [comment]
> Double Kick only hits once, it needs looking into it

I think I found what's causing this issue a left a comment on the PR.

**Comment by SheerSt** [comment]
Sorry for taking so long to get back on this. Looks really good, fantastic job. I checked through and everything seems very accurate from what I can tell.

Merging into master soon, will leave the PR open.

**Pull request merged**
